apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 76.5.1
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
