apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kps
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 76.5.1
    chart: kube-prometheus-stack
    helm:
      releaseName: kube-prometheus-stack
      parameters:
        - name: grafana.ingress.enabled
          value: 'true'
        - name: grafana.ingress.hosts[0]
          value: grafana.hostilemeow.net
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
